//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback Insert_PersonaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_PersonaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Select_PersonaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Insert_EmpresaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_EmpresaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Select_EmpresaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Insert_CategoriaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_CategoriaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Delete_CategoriaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Insert_PuestoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_PuestoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Delete_PuestoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Insert_solicitudOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_solicitudOperationCompleted;
    
    private System.Threading.SendOrPostCallback Delete_solicitudOperationCompleted;
    
    private System.Threading.SendOrPostCallback Insert_TelefonoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_TelefonoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Delete_TelefonoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Select_TelefonoOperationCompleted;
    
    private System.Threading.SendOrPostCallback Insert_IdiomaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Update_IdiomaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Delete_IdiomaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Insert_Persona_IdiomaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Delete_Persona_IdiomaOperationCompleted;
    
    private System.Threading.SendOrPostCallback Select_Persona_IdiomaOperationCompleted;
    
    private System.Threading.SendOrPostCallback QuerryOperationCompleted;
    
    /// <remarks/>
    public Service1() {
        this.Url = "http://www.webserviceitcrempleos.somee.com/Service1.asmx";
    }
    
    /// <remarks/>
    public event Insert_PersonaCompletedEventHandler Insert_PersonaCompleted;
    
    /// <remarks/>
    public event Update_PersonaCompletedEventHandler Update_PersonaCompleted;
    
    /// <remarks/>
    public event Select_PersonaCompletedEventHandler Select_PersonaCompleted;
    
    /// <remarks/>
    public event Insert_EmpresaCompletedEventHandler Insert_EmpresaCompleted;
    
    /// <remarks/>
    public event Update_EmpresaCompletedEventHandler Update_EmpresaCompleted;
    
    /// <remarks/>
    public event Select_EmpresaCompletedEventHandler Select_EmpresaCompleted;
    
    /// <remarks/>
    public event Insert_CategoriaCompletedEventHandler Insert_CategoriaCompleted;
    
    /// <remarks/>
    public event Update_CategoriaCompletedEventHandler Update_CategoriaCompleted;
    
    /// <remarks/>
    public event Delete_CategoriaCompletedEventHandler Delete_CategoriaCompleted;
    
    /// <remarks/>
    public event Insert_PuestoCompletedEventHandler Insert_PuestoCompleted;
    
    /// <remarks/>
    public event Update_PuestoCompletedEventHandler Update_PuestoCompleted;
    
    /// <remarks/>
    public event Delete_PuestoCompletedEventHandler Delete_PuestoCompleted;
    
    /// <remarks/>
    public event Insert_solicitudCompletedEventHandler Insert_solicitudCompleted;
    
    /// <remarks/>
    public event Update_solicitudCompletedEventHandler Update_solicitudCompleted;
    
    /// <remarks/>
    public event Delete_solicitudCompletedEventHandler Delete_solicitudCompleted;
    
    /// <remarks/>
    public event Insert_TelefonoCompletedEventHandler Insert_TelefonoCompleted;
    
    /// <remarks/>
    public event Update_TelefonoCompletedEventHandler Update_TelefonoCompleted;
    
    /// <remarks/>
    public event Delete_TelefonoCompletedEventHandler Delete_TelefonoCompleted;
    
    /// <remarks/>
    public event Select_TelefonoCompletedEventHandler Select_TelefonoCompleted;
    
    /// <remarks/>
    public event Insert_IdiomaCompletedEventHandler Insert_IdiomaCompleted;
    
    /// <remarks/>
    public event Update_IdiomaCompletedEventHandler Update_IdiomaCompleted;
    
    /// <remarks/>
    public event Delete_IdiomaCompletedEventHandler Delete_IdiomaCompleted;
    
    /// <remarks/>
    public event Insert_Persona_IdiomaCompletedEventHandler Insert_Persona_IdiomaCompleted;
    
    /// <remarks/>
    public event Delete_Persona_IdiomaCompletedEventHandler Delete_Persona_IdiomaCompleted;
    
    /// <remarks/>
    public event Select_Persona_IdiomaCompletedEventHandler Select_Persona_IdiomaCompleted;
    
    /// <remarks/>
    public event QuerryCompletedEventHandler QuerryCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Persona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Persona(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos) {
        object[] results = this.Invoke("Insert_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Persona(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Persona(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_PersonaAsync(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos) {
        this.Insert_PersonaAsync(correo, pasw, descrip, dir, nombre, ap1, ap2, cond, conocimientos, null);
    }
    
    /// <remarks/>
    public void Insert_PersonaAsync(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos, object userState) {
        if ((this.Insert_PersonaOperationCompleted == null)) {
            this.Insert_PersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_PersonaOperationCompleted);
        }
        this.InvokeAsync("Insert_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos}, this.Insert_PersonaOperationCompleted, userState);
    }
    
    private void OnInsert_PersonaOperationCompleted(object arg) {
        if ((this.Insert_PersonaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_PersonaCompleted(this, new Insert_PersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Persona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_Persona(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos) {
        object[] results = this.Invoke("Update_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_Persona(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_Persona(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_PersonaAsync(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos) {
        this.Update_PersonaAsync(correo, pasw, descrip, dir, nombre, ap1, ap2, cond, conocimientos, null);
    }
    
    /// <remarks/>
    public void Update_PersonaAsync(string correo, string pasw, string descrip, string dir, string nombre, string ap1, string ap2, char cond, string conocimientos, object userState) {
        if ((this.Update_PersonaOperationCompleted == null)) {
            this.Update_PersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_PersonaOperationCompleted);
        }
        this.InvokeAsync("Update_Persona", new object[] {
                    correo,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ap1,
                    ap2,
                    cond,
                    conocimientos}, this.Update_PersonaOperationCompleted, userState);
    }
    
    private void OnUpdate_PersonaOperationCompleted(object arg) {
        if ((this.Update_PersonaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_PersonaCompleted(this, new Update_PersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select_Persona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Select_Persona(string correo, string pasw) {
        object[] results = this.Invoke("Select_Persona", new object[] {
                    correo,
                    pasw});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelect_Persona(string correo, string pasw, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Select_Persona", new object[] {
                    correo,
                    pasw}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndSelect_Persona(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void Select_PersonaAsync(string correo, string pasw) {
        this.Select_PersonaAsync(correo, pasw, null);
    }
    
    /// <remarks/>
    public void Select_PersonaAsync(string correo, string pasw, object userState) {
        if ((this.Select_PersonaOperationCompleted == null)) {
            this.Select_PersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelect_PersonaOperationCompleted);
        }
        this.InvokeAsync("Select_Persona", new object[] {
                    correo,
                    pasw}, this.Select_PersonaOperationCompleted, userState);
    }
    
    private void OnSelect_PersonaOperationCompleted(object arg) {
        if ((this.Select_PersonaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Select_PersonaCompleted(this, new Select_PersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Empresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Empresa(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web) {
        object[] results = this.Invoke("Insert_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Empresa(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Empresa(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_EmpresaAsync(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web) {
        this.Insert_EmpresaAsync(mail, pasw, descrip, dir, nombre, ced, web, null);
    }
    
    /// <remarks/>
    public void Insert_EmpresaAsync(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web, object userState) {
        if ((this.Insert_EmpresaOperationCompleted == null)) {
            this.Insert_EmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_EmpresaOperationCompleted);
        }
        this.InvokeAsync("Insert_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web}, this.Insert_EmpresaOperationCompleted, userState);
    }
    
    private void OnInsert_EmpresaOperationCompleted(object arg) {
        if ((this.Insert_EmpresaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_EmpresaCompleted(this, new Insert_EmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Empresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_Empresa(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web) {
        object[] results = this.Invoke("Update_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_Empresa(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_Empresa(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_EmpresaAsync(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web) {
        this.Update_EmpresaAsync(mail, pasw, descrip, dir, nombre, ced, web, null);
    }
    
    /// <remarks/>
    public void Update_EmpresaAsync(string mail, string pasw, string descrip, string dir, string nombre, string ced, string web, object userState) {
        if ((this.Update_EmpresaOperationCompleted == null)) {
            this.Update_EmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_EmpresaOperationCompleted);
        }
        this.InvokeAsync("Update_Empresa", new object[] {
                    mail,
                    pasw,
                    descrip,
                    dir,
                    nombre,
                    ced,
                    web}, this.Update_EmpresaOperationCompleted, userState);
    }
    
    private void OnUpdate_EmpresaOperationCompleted(object arg) {
        if ((this.Update_EmpresaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_EmpresaCompleted(this, new Update_EmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select_Empresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Select_Empresa(string correo, string pasw) {
        object[] results = this.Invoke("Select_Empresa", new object[] {
                    correo,
                    pasw});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelect_Empresa(string correo, string pasw, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Select_Empresa", new object[] {
                    correo,
                    pasw}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndSelect_Empresa(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void Select_EmpresaAsync(string correo, string pasw) {
        this.Select_EmpresaAsync(correo, pasw, null);
    }
    
    /// <remarks/>
    public void Select_EmpresaAsync(string correo, string pasw, object userState) {
        if ((this.Select_EmpresaOperationCompleted == null)) {
            this.Select_EmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelect_EmpresaOperationCompleted);
        }
        this.InvokeAsync("Select_Empresa", new object[] {
                    correo,
                    pasw}, this.Select_EmpresaOperationCompleted, userState);
    }
    
    private void OnSelect_EmpresaOperationCompleted(object arg) {
        if ((this.Select_EmpresaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Select_EmpresaCompleted(this, new Select_EmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Categoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Categoria(string categoria) {
        object[] results = this.Invoke("Insert_Categoria", new object[] {
                    categoria});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Categoria(string categoria, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Categoria", new object[] {
                    categoria}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Categoria(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_CategoriaAsync(string categoria) {
        this.Insert_CategoriaAsync(categoria, null);
    }
    
    /// <remarks/>
    public void Insert_CategoriaAsync(string categoria, object userState) {
        if ((this.Insert_CategoriaOperationCompleted == null)) {
            this.Insert_CategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_CategoriaOperationCompleted);
        }
        this.InvokeAsync("Insert_Categoria", new object[] {
                    categoria}, this.Insert_CategoriaOperationCompleted, userState);
    }
    
    private void OnInsert_CategoriaOperationCompleted(object arg) {
        if ((this.Insert_CategoriaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_CategoriaCompleted(this, new Insert_CategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Categoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_Categoria(int categoriaID, string categoria) {
        object[] results = this.Invoke("Update_Categoria", new object[] {
                    categoriaID,
                    categoria});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_Categoria(int categoriaID, string categoria, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_Categoria", new object[] {
                    categoriaID,
                    categoria}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_Categoria(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_CategoriaAsync(int categoriaID, string categoria) {
        this.Update_CategoriaAsync(categoriaID, categoria, null);
    }
    
    /// <remarks/>
    public void Update_CategoriaAsync(int categoriaID, string categoria, object userState) {
        if ((this.Update_CategoriaOperationCompleted == null)) {
            this.Update_CategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_CategoriaOperationCompleted);
        }
        this.InvokeAsync("Update_Categoria", new object[] {
                    categoriaID,
                    categoria}, this.Update_CategoriaOperationCompleted, userState);
    }
    
    private void OnUpdate_CategoriaOperationCompleted(object arg) {
        if ((this.Update_CategoriaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_CategoriaCompleted(this, new Update_CategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_Categoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Delete_Categoria(int categoriaID, string categoria) {
        object[] results = this.Invoke("Delete_Categoria", new object[] {
                    categoriaID,
                    categoria});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDelete_Categoria(int categoriaID, string categoria, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Delete_Categoria", new object[] {
                    categoriaID,
                    categoria}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDelete_Categoria(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Delete_CategoriaAsync(int categoriaID, string categoria) {
        this.Delete_CategoriaAsync(categoriaID, categoria, null);
    }
    
    /// <remarks/>
    public void Delete_CategoriaAsync(int categoriaID, string categoria, object userState) {
        if ((this.Delete_CategoriaOperationCompleted == null)) {
            this.Delete_CategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_CategoriaOperationCompleted);
        }
        this.InvokeAsync("Delete_Categoria", new object[] {
                    categoriaID,
                    categoria}, this.Delete_CategoriaOperationCompleted, userState);
    }
    
    private void OnDelete_CategoriaOperationCompleted(object arg) {
        if ((this.Delete_CategoriaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Delete_CategoriaCompleted(this, new Delete_CategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Puesto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Puesto(string puesto, int categoria_ID) {
        object[] results = this.Invoke("Insert_Puesto", new object[] {
                    puesto,
                    categoria_ID});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Puesto(string puesto, int categoria_ID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Puesto", new object[] {
                    puesto,
                    categoria_ID}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Puesto(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_PuestoAsync(string puesto, int categoria_ID) {
        this.Insert_PuestoAsync(puesto, categoria_ID, null);
    }
    
    /// <remarks/>
    public void Insert_PuestoAsync(string puesto, int categoria_ID, object userState) {
        if ((this.Insert_PuestoOperationCompleted == null)) {
            this.Insert_PuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_PuestoOperationCompleted);
        }
        this.InvokeAsync("Insert_Puesto", new object[] {
                    puesto,
                    categoria_ID}, this.Insert_PuestoOperationCompleted, userState);
    }
    
    private void OnInsert_PuestoOperationCompleted(object arg) {
        if ((this.Insert_PuestoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_PuestoCompleted(this, new Insert_PuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Puesto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_Puesto(int Puesto_ID, string puesto, int categoria_ID) {
        object[] results = this.Invoke("Update_Puesto", new object[] {
                    Puesto_ID,
                    puesto,
                    categoria_ID});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_Puesto(int Puesto_ID, string puesto, int categoria_ID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_Puesto", new object[] {
                    Puesto_ID,
                    puesto,
                    categoria_ID}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_Puesto(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_PuestoAsync(int Puesto_ID, string puesto, int categoria_ID) {
        this.Update_PuestoAsync(Puesto_ID, puesto, categoria_ID, null);
    }
    
    /// <remarks/>
    public void Update_PuestoAsync(int Puesto_ID, string puesto, int categoria_ID, object userState) {
        if ((this.Update_PuestoOperationCompleted == null)) {
            this.Update_PuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_PuestoOperationCompleted);
        }
        this.InvokeAsync("Update_Puesto", new object[] {
                    Puesto_ID,
                    puesto,
                    categoria_ID}, this.Update_PuestoOperationCompleted, userState);
    }
    
    private void OnUpdate_PuestoOperationCompleted(object arg) {
        if ((this.Update_PuestoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_PuestoCompleted(this, new Update_PuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_Puesto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Delete_Puesto(int Puesto_ID) {
        object[] results = this.Invoke("Delete_Puesto", new object[] {
                    Puesto_ID});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDelete_Puesto(int Puesto_ID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Delete_Puesto", new object[] {
                    Puesto_ID}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDelete_Puesto(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Delete_PuestoAsync(int Puesto_ID) {
        this.Delete_PuestoAsync(Puesto_ID, null);
    }
    
    /// <remarks/>
    public void Delete_PuestoAsync(int Puesto_ID, object userState) {
        if ((this.Delete_PuestoOperationCompleted == null)) {
            this.Delete_PuestoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_PuestoOperationCompleted);
        }
        this.InvokeAsync("Delete_Puesto", new object[] {
                    Puesto_ID}, this.Delete_PuestoOperationCompleted, userState);
    }
    
    private void OnDelete_PuestoOperationCompleted(object arg) {
        if ((this.Delete_PuestoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Delete_PuestoCompleted(this, new Delete_PuestoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_solicitud", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_solicitud(string mail, System.DateTime fecha, char Estado) {
        object[] results = this.Invoke("Insert_solicitud", new object[] {
                    mail,
                    fecha,
                    Estado});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_solicitud(string mail, System.DateTime fecha, char Estado, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_solicitud", new object[] {
                    mail,
                    fecha,
                    Estado}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_solicitud(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_solicitudAsync(string mail, System.DateTime fecha, char Estado) {
        this.Insert_solicitudAsync(mail, fecha, Estado, null);
    }
    
    /// <remarks/>
    public void Insert_solicitudAsync(string mail, System.DateTime fecha, char Estado, object userState) {
        if ((this.Insert_solicitudOperationCompleted == null)) {
            this.Insert_solicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_solicitudOperationCompleted);
        }
        this.InvokeAsync("Insert_solicitud", new object[] {
                    mail,
                    fecha,
                    Estado}, this.Insert_solicitudOperationCompleted, userState);
    }
    
    private void OnInsert_solicitudOperationCompleted(object arg) {
        if ((this.Insert_solicitudCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_solicitudCompleted(this, new Insert_solicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_solicitud", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_solicitud(int SolicitudID, string mail, char Estado) {
        object[] results = this.Invoke("Update_solicitud", new object[] {
                    SolicitudID,
                    mail,
                    Estado});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_solicitud(int SolicitudID, string mail, char Estado, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_solicitud", new object[] {
                    SolicitudID,
                    mail,
                    Estado}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_solicitud(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_solicitudAsync(int SolicitudID, string mail, char Estado) {
        this.Update_solicitudAsync(SolicitudID, mail, Estado, null);
    }
    
    /// <remarks/>
    public void Update_solicitudAsync(int SolicitudID, string mail, char Estado, object userState) {
        if ((this.Update_solicitudOperationCompleted == null)) {
            this.Update_solicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_solicitudOperationCompleted);
        }
        this.InvokeAsync("Update_solicitud", new object[] {
                    SolicitudID,
                    mail,
                    Estado}, this.Update_solicitudOperationCompleted, userState);
    }
    
    private void OnUpdate_solicitudOperationCompleted(object arg) {
        if ((this.Update_solicitudCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_solicitudCompleted(this, new Update_solicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_solicitud", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Delete_solicitud(int SolicitudID, string mail) {
        object[] results = this.Invoke("Delete_solicitud", new object[] {
                    SolicitudID,
                    mail});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDelete_solicitud(int SolicitudID, string mail, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Delete_solicitud", new object[] {
                    SolicitudID,
                    mail}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDelete_solicitud(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Delete_solicitudAsync(int SolicitudID, string mail) {
        this.Delete_solicitudAsync(SolicitudID, mail, null);
    }
    
    /// <remarks/>
    public void Delete_solicitudAsync(int SolicitudID, string mail, object userState) {
        if ((this.Delete_solicitudOperationCompleted == null)) {
            this.Delete_solicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_solicitudOperationCompleted);
        }
        this.InvokeAsync("Delete_solicitud", new object[] {
                    SolicitudID,
                    mail}, this.Delete_solicitudOperationCompleted, userState);
    }
    
    private void OnDelete_solicitudOperationCompleted(object arg) {
        if ((this.Delete_solicitudCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Delete_solicitudCompleted(this, new Delete_solicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Telefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Telefono(string mail, string Telefono) {
        object[] results = this.Invoke("Insert_Telefono", new object[] {
                    mail,
                    Telefono});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Telefono(string mail, string Telefono, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Telefono", new object[] {
                    mail,
                    Telefono}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Telefono(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_TelefonoAsync(string mail, string Telefono) {
        this.Insert_TelefonoAsync(mail, Telefono, null);
    }
    
    /// <remarks/>
    public void Insert_TelefonoAsync(string mail, string Telefono, object userState) {
        if ((this.Insert_TelefonoOperationCompleted == null)) {
            this.Insert_TelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_TelefonoOperationCompleted);
        }
        this.InvokeAsync("Insert_Telefono", new object[] {
                    mail,
                    Telefono}, this.Insert_TelefonoOperationCompleted, userState);
    }
    
    private void OnInsert_TelefonoOperationCompleted(object arg) {
        if ((this.Insert_TelefonoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_TelefonoCompleted(this, new Insert_TelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Telefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_Telefono(int SolicitudID, string mail, char Estado) {
        object[] results = this.Invoke("Update_Telefono", new object[] {
                    SolicitudID,
                    mail,
                    Estado});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_Telefono(int SolicitudID, string mail, char Estado, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_Telefono", new object[] {
                    SolicitudID,
                    mail,
                    Estado}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_Telefono(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_TelefonoAsync(int SolicitudID, string mail, char Estado) {
        this.Update_TelefonoAsync(SolicitudID, mail, Estado, null);
    }
    
    /// <remarks/>
    public void Update_TelefonoAsync(int SolicitudID, string mail, char Estado, object userState) {
        if ((this.Update_TelefonoOperationCompleted == null)) {
            this.Update_TelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_TelefonoOperationCompleted);
        }
        this.InvokeAsync("Update_Telefono", new object[] {
                    SolicitudID,
                    mail,
                    Estado}, this.Update_TelefonoOperationCompleted, userState);
    }
    
    private void OnUpdate_TelefonoOperationCompleted(object arg) {
        if ((this.Update_TelefonoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_TelefonoCompleted(this, new Update_TelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_Telefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Delete_Telefono(int SolicitudID, string mail) {
        object[] results = this.Invoke("Delete_Telefono", new object[] {
                    SolicitudID,
                    mail});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDelete_Telefono(int SolicitudID, string mail, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Delete_Telefono", new object[] {
                    SolicitudID,
                    mail}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDelete_Telefono(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Delete_TelefonoAsync(int SolicitudID, string mail) {
        this.Delete_TelefonoAsync(SolicitudID, mail, null);
    }
    
    /// <remarks/>
    public void Delete_TelefonoAsync(int SolicitudID, string mail, object userState) {
        if ((this.Delete_TelefonoOperationCompleted == null)) {
            this.Delete_TelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_TelefonoOperationCompleted);
        }
        this.InvokeAsync("Delete_Telefono", new object[] {
                    SolicitudID,
                    mail}, this.Delete_TelefonoOperationCompleted, userState);
    }
    
    private void OnDelete_TelefonoOperationCompleted(object arg) {
        if ((this.Delete_TelefonoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Delete_TelefonoCompleted(this, new Delete_TelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select_Telefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Select_Telefono(string correo) {
        object[] results = this.Invoke("Select_Telefono", new object[] {
                    correo});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelect_Telefono(string correo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Select_Telefono", new object[] {
                    correo}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndSelect_Telefono(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void Select_TelefonoAsync(string correo) {
        this.Select_TelefonoAsync(correo, null);
    }
    
    /// <remarks/>
    public void Select_TelefonoAsync(string correo, object userState) {
        if ((this.Select_TelefonoOperationCompleted == null)) {
            this.Select_TelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelect_TelefonoOperationCompleted);
        }
        this.InvokeAsync("Select_Telefono", new object[] {
                    correo}, this.Select_TelefonoOperationCompleted, userState);
    }
    
    private void OnSelect_TelefonoOperationCompleted(object arg) {
        if ((this.Select_TelefonoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Select_TelefonoCompleted(this, new Select_TelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Idioma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Idioma(string idioma) {
        object[] results = this.Invoke("Insert_Idioma", new object[] {
                    idioma});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Idioma(string idioma, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Idioma", new object[] {
                    idioma}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Idioma(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_IdiomaAsync(string idioma) {
        this.Insert_IdiomaAsync(idioma, null);
    }
    
    /// <remarks/>
    public void Insert_IdiomaAsync(string idioma, object userState) {
        if ((this.Insert_IdiomaOperationCompleted == null)) {
            this.Insert_IdiomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_IdiomaOperationCompleted);
        }
        this.InvokeAsync("Insert_Idioma", new object[] {
                    idioma}, this.Insert_IdiomaOperationCompleted, userState);
    }
    
    private void OnInsert_IdiomaOperationCompleted(object arg) {
        if ((this.Insert_IdiomaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_IdiomaCompleted(this, new Insert_IdiomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Idioma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Update_Idioma(int IdiomaID, string idioma) {
        object[] results = this.Invoke("Update_Idioma", new object[] {
                    IdiomaID,
                    idioma});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate_Idioma(int IdiomaID, string idioma, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update_Idioma", new object[] {
                    IdiomaID,
                    idioma}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdate_Idioma(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Update_IdiomaAsync(int IdiomaID, string idioma) {
        this.Update_IdiomaAsync(IdiomaID, idioma, null);
    }
    
    /// <remarks/>
    public void Update_IdiomaAsync(int IdiomaID, string idioma, object userState) {
        if ((this.Update_IdiomaOperationCompleted == null)) {
            this.Update_IdiomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_IdiomaOperationCompleted);
        }
        this.InvokeAsync("Update_Idioma", new object[] {
                    IdiomaID,
                    idioma}, this.Update_IdiomaOperationCompleted, userState);
    }
    
    private void OnUpdate_IdiomaOperationCompleted(object arg) {
        if ((this.Update_IdiomaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Update_IdiomaCompleted(this, new Update_IdiomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_Idioma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Delete_Idioma(int IdiomaID) {
        object[] results = this.Invoke("Delete_Idioma", new object[] {
                    IdiomaID});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDelete_Idioma(int IdiomaID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Delete_Idioma", new object[] {
                    IdiomaID}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDelete_Idioma(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Delete_IdiomaAsync(int IdiomaID) {
        this.Delete_IdiomaAsync(IdiomaID, null);
    }
    
    /// <remarks/>
    public void Delete_IdiomaAsync(int IdiomaID, object userState) {
        if ((this.Delete_IdiomaOperationCompleted == null)) {
            this.Delete_IdiomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_IdiomaOperationCompleted);
        }
        this.InvokeAsync("Delete_Idioma", new object[] {
                    IdiomaID}, this.Delete_IdiomaOperationCompleted, userState);
    }
    
    private void OnDelete_IdiomaOperationCompleted(object arg) {
        if ((this.Delete_IdiomaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Delete_IdiomaCompleted(this, new Delete_IdiomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Persona_Idioma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Insert_Persona_Idioma(string mail, int idiomaID) {
        object[] results = this.Invoke("Insert_Persona_Idioma", new object[] {
                    mail,
                    idiomaID});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInsert_Persona_Idioma(string mail, int idiomaID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Insert_Persona_Idioma", new object[] {
                    mail,
                    idiomaID}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndInsert_Persona_Idioma(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Insert_Persona_IdiomaAsync(string mail, int idiomaID) {
        this.Insert_Persona_IdiomaAsync(mail, idiomaID, null);
    }
    
    /// <remarks/>
    public void Insert_Persona_IdiomaAsync(string mail, int idiomaID, object userState) {
        if ((this.Insert_Persona_IdiomaOperationCompleted == null)) {
            this.Insert_Persona_IdiomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_Persona_IdiomaOperationCompleted);
        }
        this.InvokeAsync("Insert_Persona_Idioma", new object[] {
                    mail,
                    idiomaID}, this.Insert_Persona_IdiomaOperationCompleted, userState);
    }
    
    private void OnInsert_Persona_IdiomaOperationCompleted(object arg) {
        if ((this.Insert_Persona_IdiomaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Insert_Persona_IdiomaCompleted(this, new Insert_Persona_IdiomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_Persona_Idioma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Delete_Persona_Idioma(string mail, int idiomaID) {
        object[] results = this.Invoke("Delete_Persona_Idioma", new object[] {
                    mail,
                    idiomaID});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDelete_Persona_Idioma(string mail, int idiomaID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Delete_Persona_Idioma", new object[] {
                    mail,
                    idiomaID}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDelete_Persona_Idioma(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void Delete_Persona_IdiomaAsync(string mail, int idiomaID) {
        this.Delete_Persona_IdiomaAsync(mail, idiomaID, null);
    }
    
    /// <remarks/>
    public void Delete_Persona_IdiomaAsync(string mail, int idiomaID, object userState) {
        if ((this.Delete_Persona_IdiomaOperationCompleted == null)) {
            this.Delete_Persona_IdiomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_Persona_IdiomaOperationCompleted);
        }
        this.InvokeAsync("Delete_Persona_Idioma", new object[] {
                    mail,
                    idiomaID}, this.Delete_Persona_IdiomaOperationCompleted, userState);
    }
    
    private void OnDelete_Persona_IdiomaOperationCompleted(object arg) {
        if ((this.Delete_Persona_IdiomaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Delete_Persona_IdiomaCompleted(this, new Delete_Persona_IdiomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select_Persona_Idioma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Select_Persona_Idioma(string mail) {
        object[] results = this.Invoke("Select_Persona_Idioma", new object[] {
                    mail});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSelect_Persona_Idioma(string mail, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Select_Persona_Idioma", new object[] {
                    mail}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndSelect_Persona_Idioma(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void Select_Persona_IdiomaAsync(string mail) {
        this.Select_Persona_IdiomaAsync(mail, null);
    }
    
    /// <remarks/>
    public void Select_Persona_IdiomaAsync(string mail, object userState) {
        if ((this.Select_Persona_IdiomaOperationCompleted == null)) {
            this.Select_Persona_IdiomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelect_Persona_IdiomaOperationCompleted);
        }
        this.InvokeAsync("Select_Persona_Idioma", new object[] {
                    mail}, this.Select_Persona_IdiomaOperationCompleted, userState);
    }
    
    private void OnSelect_Persona_IdiomaOperationCompleted(object arg) {
        if ((this.Select_Persona_IdiomaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.Select_Persona_IdiomaCompleted(this, new Select_Persona_IdiomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Querry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataTable Querry(string tabla) {
        object[] results = this.Invoke("Querry", new object[] {
                    tabla});
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQuerry(string tabla, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Querry", new object[] {
                    tabla}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataTable EndQuerry(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataTable)(results[0]));
    }
    
    /// <remarks/>
    public void QuerryAsync(string tabla) {
        this.QuerryAsync(tabla, null);
    }
    
    /// <remarks/>
    public void QuerryAsync(string tabla, object userState) {
        if ((this.QuerryOperationCompleted == null)) {
            this.QuerryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerryOperationCompleted);
        }
        this.InvokeAsync("Querry", new object[] {
                    tabla}, this.QuerryOperationCompleted, userState);
    }
    
    private void OnQuerryOperationCompleted(object arg) {
        if ((this.QuerryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QuerryCompleted(this, new QuerryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_PersonaCompletedEventHandler(object sender, Insert_PersonaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_PersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_PersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_PersonaCompletedEventHandler(object sender, Update_PersonaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_PersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_PersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Select_PersonaCompletedEventHandler(object sender, Select_PersonaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Select_PersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Select_PersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_EmpresaCompletedEventHandler(object sender, Insert_EmpresaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_EmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_EmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_EmpresaCompletedEventHandler(object sender, Update_EmpresaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_EmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_EmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Select_EmpresaCompletedEventHandler(object sender, Select_EmpresaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Select_EmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Select_EmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_CategoriaCompletedEventHandler(object sender, Insert_CategoriaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_CategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_CategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_CategoriaCompletedEventHandler(object sender, Update_CategoriaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_CategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_CategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Delete_CategoriaCompletedEventHandler(object sender, Delete_CategoriaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Delete_CategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Delete_CategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_PuestoCompletedEventHandler(object sender, Insert_PuestoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_PuestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_PuestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_PuestoCompletedEventHandler(object sender, Update_PuestoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_PuestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_PuestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Delete_PuestoCompletedEventHandler(object sender, Delete_PuestoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Delete_PuestoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Delete_PuestoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_solicitudCompletedEventHandler(object sender, Insert_solicitudCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_solicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_solicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_solicitudCompletedEventHandler(object sender, Update_solicitudCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_solicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_solicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Delete_solicitudCompletedEventHandler(object sender, Delete_solicitudCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Delete_solicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Delete_solicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_TelefonoCompletedEventHandler(object sender, Insert_TelefonoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_TelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_TelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_TelefonoCompletedEventHandler(object sender, Update_TelefonoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_TelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_TelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Delete_TelefonoCompletedEventHandler(object sender, Delete_TelefonoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Delete_TelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Delete_TelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Select_TelefonoCompletedEventHandler(object sender, Select_TelefonoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Select_TelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Select_TelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_IdiomaCompletedEventHandler(object sender, Insert_IdiomaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_IdiomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_IdiomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Update_IdiomaCompletedEventHandler(object sender, Update_IdiomaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Update_IdiomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Update_IdiomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Delete_IdiomaCompletedEventHandler(object sender, Delete_IdiomaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Delete_IdiomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Delete_IdiomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Insert_Persona_IdiomaCompletedEventHandler(object sender, Insert_Persona_IdiomaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Insert_Persona_IdiomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Insert_Persona_IdiomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Delete_Persona_IdiomaCompletedEventHandler(object sender, Delete_Persona_IdiomaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Delete_Persona_IdiomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Delete_Persona_IdiomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void Select_Persona_IdiomaCompletedEventHandler(object sender, Select_Persona_IdiomaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Select_Persona_IdiomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal Select_Persona_IdiomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void QuerryCompletedEventHandler(object sender, QuerryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QuerryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QuerryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataTable Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataTable)(this.results[0]));
        }
    }
}
